# Generated by Django 3.0.2 on 2020-01-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app24', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='idno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
